title = "Rohan Prasad"
baseURL = "//localhost:8080/"
canonifyURLs = false
relativeURLs = true
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Personal Website for Rohan Prasad"
  # facebook = ""
  # twitter = ""
  # instagram = "https://www.instagram.com/brohanprasquad/"
  # youtube = ""
  github = "https://github.com/rp4fx12"
  linkedin = "https://linkedin.com/in/rohanpra"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  featured_image = "/images/banner.jpg"